export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const CURRENT_CONSTRUCTOR = "CURRENT_CONSTRUCTOR";
export const CURRENT_INGREDIENT = "CURRENT_INGREDIENT";
export const CREATED_ORDER = "CREATED_ORDER";



