export const WS_PROFILE_CONNECTION_START: "WS_PROFILE_CONNECTION_START" =
  "WS_PROFILE_CONNECTION_START";
export const WS_PROFILE_CONNECTION_SUCCESS: "WS_PROFILE_CONNECTION_SUCCESS" =
  "WS_PROFILE_CONNECTION_SUCCESS";
export const WS_PROFILE_CONNECTION_ERROR: "WS_PROFILE_CONNECTION_ERROR" =
  "WS_PROFILE_CONNECTION_ERROR";
export const WS_PROFILE_CONNECTION_CLOSED: "WS_PROFILE_CONNECTION_CLOSED" =
  "WS_PROFILE_CONNECTION_CLOSED";
export const WS_PROFILE_GET_MESSAGE: "WS_PROFILE_GET_MESSAGE" =
  "WS_PROFILE_GET_MESSAGE";
export const WS_PROFILE_SEND_MESSAGE: "WS_PROFILE_SEND_MESSAGE" =
  "WS_PROFILE_SEND_MESSAGE";
export const WS_PROFILE_CURRENT_ORDER: "WS_PROFILE_CURRENT_ORDER" =
  "WS_PROFILE_CURRENT_ORDER";
export const WS_PROFILE_CLOSE_CONNECTION: "WS_PROFILE_CLOSE_CONNECTION" =
  "WS_PROFILE_CLOSE_CONNECTION";